services:
  zookeeper:
    restart: unless-stopped
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - elastiflow-grafana

  kafka_broker:
    restart: unless-stopped
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092,PLAINTEXT_INTERNAL://kafka_broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - elastiflow-grafana
    healthcheck:
      test: nc -z 127.0.0.1 9092 || exit -1
      interval: 10s
      retries: 5
      start_period: 8s

  victorialogs:
    restart: unless-stopped
    image: docker.io/victoriametrics/victoria-logs:${VMLOG_VERSION}
    stdin_open: true
    tty: true
    volumes:
      - victorialogs-data:/victorialogs-data
    command: -storageDataPath=victorialogs-data -retentionPeriod=${LOG_RETENTION}
    networks:
      - elastiflow-grafana

  grafana:    
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource
    volumes:
      - 'grafana-data:/var/lib/grafana'
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: victorialogs
          type: victoriametrics-logs-datasource
          access: proxy 
          orgId: 1
          url: http://victorialogs:9428
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        EOF
        /run.sh
    image: grafana/grafana:latest
    networks:
      - elastiflow-grafana
  
  alloy:
    restart: unless-stopped
    image: grafana/alloy:latest
    depends_on:
      kafka_broker:
        condition: service_healthy
    #ports:
      #- "9901:9901"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: ["run", "--server.http.listen-addr=0.0.0.0:9901", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
    networks:
      - elastiflow-grafana

networks:
  elastiflow-grafana:

volumes:
  grafana-data:
  victorialogs-data:
