{
 "title": "Exporters - Traffic",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Ingress Interface (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(observer_ingress_interface_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [1m])*8/(60000/1000))"
    },
    {
     "direction": "backward",
     "expr": "sum by(network_bytes) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [1m])*8/(60000/1000))"
    }
   ]
  },
  {
   "title": "Egress Interface (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(observer_egress_interface_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [1m])*8/(60000/1000))"
    },
    {
     "direction": "backward",
     "expr": "sum by(network_bytes) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [1m])*8/(60000/1000))"
    }
   ]
  },
  {
   "title": "Ingress Interface (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(observer_ingress_interface_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_packets [1m])*8/(60000/1000))"
    },
    {
     "direction": "backward",
     "expr": "sum by(network_packets) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_packets [1m])*8/(60000/1000))"
    }
   ]
  },
  {
   "title": "Egress Interface (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(observer_egress_interface_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_packets [1m])*8/(60000/1000))"
    },
    {
     "direction": "backward",
     "expr": "sum by(network_packets) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_packets [1m])*8/(60000/1000))"
    }
   ]
  }
 ]
}