{
 "title": "Exporters - Metrics",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Observed Traffic (records)",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"elastiflow\"} | json | keep host_name, flow_export_version_name, network_bytes, network_packets",
     "maxLines": 10000
    }
   ]
  },
  {
   "title": "Observed Traffic (flow records/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(host_name) (count_over_time({service_name=\"elastiflow\"} | json | host_name!=`` [$__interval])) / (60000/1000)"
    }
   ]
  },
  {
   "title": "Observed Traffic (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(host_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [$__interval])*8/(60000/1000))"
    }
   ]
  },
  {
   "title": "Observed Traffic (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(host_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_packets [$__interval])/(60000/1000))"
    }
   ]
  }
 ]
}