{
 "title": "Flow Records",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Flow Records",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"elastiflow\"} | json | client_ip!=``, server_ip!=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Observed Traffic (flow records/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(flow_export_version_name) (count_over_time({service_name=\"elastiflow\"} | json | client_ip!=``, server_ip!=`` [$__interval])) / (60000/1000)"
    }
   ]
  },
  {
   "title": "Conversations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count(count_over_time({service_name=\"elastiflow\"} | json [$__auto])) by (flow_conversation_id))"
    }
   ]
  },
  {
   "title": "Records",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"elastiflow\"} | json | keep flow_export_version_name, flow_conversation_id, host_name, client_domain, server_domain, flow_server_l4_port_name, network_bytes, network_packets",
     "maxLines": 10000
    }
   ]
  }
 ]
}