{
 "title": "GeoIP",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Client Countries (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(client_geo_country_name) (count_over_time({service_name=\"elastiflow\"} | json | client_geo_country_name != `` [$__interval]))"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 24, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"elastiflow\"} | pattern `<_>client.domain\":\"<client_domain>\"<_>\"client.geo.location\":\"<lat>,<long>\"<_>client.ip\":\"<client_ip>\"<_>network.bytes\":<network_bytes>,<_>network.packets\":<network_packets>,<_>` | keep client_domain, client_ip, network_bytes, network_packets, lat, long | lat!=``, long!=``"
    },
    {
     "direction": "backward",
     "expr": "{service=\"elastiflow\"} | pattern `<_>network.bytes\":<network_bytes>,<_>network.packets\":<network_packets>,<_>server.domain\":\"<server_domain>\"<_>\"server.geo.location\":\"<lat>,<long>\"<_>server.ip\":\"<server_ip>\"<_>` | keep network_bytes, network_packets, server_domain, server_ip, lat, long | lat!=``, long!=``"
    }
   ]
  },
  {
   "title": "Server Countries (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(server_geo_country_name) (count_over_time({service_name=\"elastiflow\"} | json | server_geo_country_name != `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Client Cities (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(client_geo_city_name) (count_over_time({service_name=\"elastiflow\"} | json | client_geo_city_name != `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Server Cities (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(server_geo_city_name) (count_over_time({service_name=\"elastiflow\"} | json | server_geo_city_name != `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Client Time Zones (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(flow_client_geo_tz_name) (count_over_time({service_name=\"elastiflow\"} | json | flow_client_geo_tz_name != `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Server Time Zones (flow records)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(flow_server_geo_tz_name) (count_over_time({service_name=\"elastiflow\"} | json | flow_server_geo_tz_name != `` [$__interval]))"
    }
   ]
  }
 ]
}