{
 "title": "Overview",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "flowexp", "label": "Flow Exporter", "query": { "query": "" } },
   { "name": "client", "label": "Client", "query": { "query": "" } },
   { "name": "server", "label": "Server", "query": { "query": "" } },
   { "name": "service", "label": "Service", "query": { "query": "" } },
   { "name": "sessionest", "label": "Session Established", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Clients (bytes)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | client.domain:* | stats by (client.domain) sum(network.bytes) network.bytes.total | last 20 by(network.bytes.total)"
    }
   ]
  },
  {
   "title": "Services (bytes)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | flow.server.l4.port.name:* | stats by (flow.server.l4.port.name) sum(network.bytes) network.bytes.total | last 20 by(network.bytes.total)"
    }
   ]
  },
  {
   "title": "TCP Flags",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | tcp.flags.tags:* | stats by (tcp.flags.tags) count() tcp.flags.tags.count | last 20 by(tcp.flags.tags.count)"
    }
   ]
  },
  {
   "title": "Servers (bytes)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | server.domain:* | stats by (server.domain) sum(network.bytes) network.bytes.total | last 20 by(network.bytes.total)"
    }
   ]
  },
  {
   "title": "IPv4 Protocols (bytes)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | network.transport:* | stats by (network.transport) sum(network.bytes) network.bytes.total | last 20 by(network.bytes.total)"
    }
   ]
  },
  {
   "title": "Threat ID",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND client.domain:contains_any(${client:doublequote}) AND server.domain:contains_any(${server:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | sec.threat.name:* | unroll sec.threat.name | stats by (sec.threat.name) count() sec.threat.name.count | last 16 by(sec.threat.name.count)"
    }
   ]
  }
 ]
}