{
 "title": "Threats",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "flowexp", "label": "Flow Exporter", "query": { "query": "" } },
   { "name": "service", "label": "Service", "query": { "query": "" } },
   { "name": "sessionest", "label": "Session Established", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Flow Records",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | sec.threat.name:* (-network.community_id:=`` OR -flow.conversation.id:=``) | stats count(sec.threat.name)"
    }
   ]
  },
  {
   "title": "Threats (Count)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | network.community_id:* sec.threat.name: * | unroll sec.threat.name | stats by (sec.threat.name) count_uniq(network.community_id) threatcount | last 25 by(threatcount)"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | sec.threat.name:* | stats count_uniq(network.community_id)"
    }
   ]
  },
  {
   "title": "Threats",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | sec.threat.name:* network.community_id:* | keep sec.threat.name, network.community_id | unroll sec.threat.name",
     "maxLines": 1000000
    }
   ]
  },
  {
   "title": "Public Threats",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | -flow.client.as.label:=\"PRIVATE\" client.domain:* client.ip:* sec.threat.name:* network.community_id:* | keep client.domain, client.ip, network.community_id",
     "maxLines": 1000000
    }
   ]
  },
  {
   "title": "High-Risk Clients",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | flow.client.as.label:=\"PRIVATE\" client.domain:* client.ip:* sec.threat.name:* network.community_id:* | keep client.domain, client.ip, network.community_id"
    }
   ]
  },
  {
   "title": "At-Risk Servers",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | host.name:contains_any(${flowexp:doublequote}) AND flow.server.l4.port.name:contains_any(${service:doublequote}) AND l4.session.established:contains_any(${sessionest:doublequote}) | flow.server.as.label:=\"PRIVATE\" server.domain:* server.ip:* sec.threat.name:* network.community_id:* | keep server.domain, server.ip, network.community_id"
    }
   ]
  }
 ]
}