{
 "title": "Top-N - Talkers",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Throughput (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(flow_server_l4_port_name) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [$__interval])*8/(60000/1000)))"
    },
    {
     "direction": "backward",
     "expr": "sum by(network_bytes) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [$__interval])*8/(60000/1000))"
    }
   ]
  },
  {
   "title": "Top Servers (bytes)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(server_domain) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [1m])))"
    }
   ]
  },
  {
   "title": "Top Clients (bytes)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(client_domain) (sum_over_time({service_name=\"elastiflow\"} | json | unwrap network_bytes [$__auto])))"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"elastiflow\"} | json | keep client_domain, client_ip, network_bytes, network_packets, network_community_id",
     "maxLines": 10000
    }
   ]
  },
  {
   "title": "Top Servers",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"elastiflow\"} | json | keep server_domain, server_ip, network_bytes, network_packets, network_community_id",
     "maxLines": 10000
    }
   ]
  }
 ]
}