{
 "title": "Traffic Details",
 "tags": [ "ElastiFlow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "IP Versions (Flow Records)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.type:* | stats by (network.type) count()"
    }
   ]
  },
  {
   "title": "IP Versions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.type:* | stats count_uniq(network.type)"
    }
   ]
  },
  {
   "title": "Layer-4 Protocol (flow records)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.transport:* | stats by (network.transport) count()"
    }
   ]
  },
  {
   "title": "Layer-4 Protocols",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.transport:* | stats count_uniq(network.transport)"
    }
   ]
  },
  {
   "title": "IP Versions (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.type:* | stats by (network.type) sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as throughput | del network.bytes.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | stats sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as Throughput | del network.bytes.total"
    }
   ]
  },
  {
   "title": "Layer-4 Protocols (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.transport:* | stats by (network.transport) sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as throughput | del network.bytes.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | stats sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as Throughput | del network.bytes.total"
    }
   ]
  },
  {
   "title": "IP Versions (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.type:* | stats by (network.type) sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as throughput | del network.packets.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | stats sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as Throughput | del network.packets.total"
    }
   ]
  },
  {
   "title": "Layer-4 Protocols (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | network.transport:* | stats by (network.transport) sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as throughput | del network.packets.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | stats sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as Throughput | del network.packets.total"
    }
   ]
  },
  {
   "title": "VLANs (flow records)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | vlan.tag.id:* | stats by (vlan.tag.id) count()"
    }
   ]
  },
  {
   "title": "DSCP (flow records)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | flow.in.ip.dscp.name:* | stats by (flow.in.ip.dscp.name) count()"
    }
   ]
  },
  {
   "title": "Throughput/VLAN (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | vlan.tag.id:* | stats by (vlan.tag.id) sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as throughput | del network.bytes.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | vlan.tag.id:* | stats sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as Throughput | del network.bytes.total"
    }
   ]
  },
  {
   "title": "DSCP (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | flow.in.ip.dscp.name:* | stats by (flow.in.ip.dscp.name) sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as throughput | del network.bytes.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | flow.in.ip.dscp.name:* | stats sum(network.bytes) network.bytes.total | math network.bytes.total*8/(60000/1000) as Throughput | del network.bytes.total"
    }
   ]
  },
  {
   "title": "Throughput/VLAN (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | vlan.tag.id:* | stats by (vlan.tag.id) sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as throughput | del network.packets.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | vlan.tag.id:* | stats sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as Throughput | del network.packets.total"
    }
   ]
  },
  {
   "title": "DSCP (pkts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "{service=\"elastiflow\"} | flow.in.ip.dscp.name:* | stats by (flow.in.ip.dscp.name) sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as throughput | del network.packets.total"
    },
    {
     "expr": "{service=\"elastiflow\"} | flow.in.ip.dscp.name:* | stats sum(network.packets) network.packets.total | math network.packets.total/(60000/1000) as Throughput | del network.packets.total"
    }
   ]
  }
 ]
}